### PR TITLE
Add common problem

### PR DESCRIPTION
**Pull request by coastalwhite**
After many weeks of fiddling on the Friday, I managed to get a Correlation Power Analysis attack working on the DesignStart chip. This shows that it indeed works! Here is one of the most confusing things I encountered and took me an oscilloscope to debug.

Hopefully this may help future users.

### CODE REVIEW

**Review by jpcrypt — CHANGES_REQUESTED** [review]
I'd prefer this to be a note under the "Done!" section above, worded to indicate that after programming the bitfile, a manual reset via the switch may be required to bring the Cortex to life.
A brief reference to this in the "Debugging" section would also be useful (i.e. "Did you reset the processor?").

**Comment by jpcrypt** [comment]
Thanks for all these fixes! Apologies for the delay in getting to this. I'll merge after you fix the reset issue.

**Comment by colinoflynn** [comment]
Also wanted to say thanks @coastalwhite - we discussed when it came in and I think then forgot to respond in the moment, and just got reminded on your latest commit. Great to see people using it, you never know with FOSS when it goes into the world what happens after.

**Comment by coastalwhite** [comment]
I am actually still actively changing and tweaking the design. Since I am trying to do clock glitches with the DesignStart core, there are some things I need to get in place for that. I have a working version, but am still working on having a reliable reset from a USB signal without pressing the SW4 button.

When I am done I will type up a small part on what is needed to do clock glitches on the design as I think that might save others  whole lot of hassle. As for this PR, the commits got a bit messy. If you don't mind I will create a new PR with the changes you requested.

**Comment by coastalwhite** [comment]
Another question. Do you want me to update the (or add a) Jupyter notebook with the glitching setup code? It took me quite some while to scrape all the information from the available resources.

**Comment by jpcrypt** [comment]
Hi Gijs,
A working glitch example setup would of course be welcome.
As for resetting under Python control, I understand the need for that, and it's easy to do- it's actually already done in our [DesignStartTrace](https://github.com/newaetech/DesignStartTrace) variant, which takes what's here and wraps it with extra functionality to sniff and trigger from Arm debug trace data. One of the things added there is a Cortex reset that's controlled by a simple `fpga_write()`
Did you end up having to make any changes to have clock glitches go through? If not, you could migrate over to the DesignStartTrace and have reset available right away. Look at the TraceWhisperer.ipynb notebook in that repo, but I think all you need to do resets is:
```
from chipwhisperer.capture.trace.TraceWhisperer import TraceWhisperer
trace = TraceWhisperer(target, scope)
trace.reset_fpga()
```
Otherwise I can add this reset functionality to this repo too. Easy for me to do and it would serve as a starting block for any other extras like this that people may wish to add in the future. Let me know!

**Comment by jpcrypt** [comment]
Ah I just saw what you did for the clock and reset in PR3. Will add thoughts and comments there.

**Pull request closed without merging**
